format = """
$os$username$hostname | \
$directory\
$rust\
$time\
$line_break\
$battery\
$status\
$shell\
$character
"""

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold yellow'

[hostname]
ssh_only = false
format = '@[$ssh_symbol$hostname]($style)'
style = 'bold green'

[os]
disabled = false

[os.symbols]
Arch = "󰣇 "
Macos = " "
Windows = " "

[time]
disabled = false

[status]
disabled = false
format = "[$status]($style) "

# [shell]
# disabled = false
# fish_indicator = " "
