; inherits: latex
; https://github.com/lervag/vimtex/blob/9df79e15bf035d1cfb32c11fffed38dd7b6a0501/autoload/vimtex/syntax/core.vim#L1404
; non-math
; those two don't seem to be their own query, fuck
; (((word) @Conceal (#eq? @Conceal "``")) (#set! conceal "“"))
; (((word) @Conceal (#eq? @Conceal "''")) (#set! conceal "”"))
(((command_name) @Conceal (#eq? @Conceal "\\\\")) (#set! conceal "⏎"))

; =====

; Spacing
(((command_name) @Conceal (#eq? @Conceal "\\ ")) (#set! conceal " "))

; Logic
(((command_name) @Conceal (#eq? @Conceal "\\bigwedge")) (#set! conceal "⋀"))
(((command_name) @Conceal (#eq? @Conceal "\\bigvee")) (#set! conceal "⋁"))

(((command_name) @Conceal (#eq? @Conceal "\\forall")) (#set! conceal "∀"))
(((command_name) @Conceal (#eq? @Conceal "\\exists")) (#set! conceal "∃"))
(((command_name) @Conceal (#eq? @Conceal "\\exist")) (#set! conceal "∃"))
(((command_name) @Conceal (#eq? @Conceal "\\nexists")) (#set! conceal "∄"))
(((command_name) @Conceal (#eq? @Conceal "\\neg")) (#set! conceal "¬"))
(((command_name) @Conceal (#eq? @Conceal "\\lnot")) (#set! conceal "¬"))
(((command_name) @Conceal (#eq? @Conceal "\\land")) (#set! conceal "∧"))
(((command_name) @Conceal (#eq? @Conceal "\\lor")) (#set! conceal "∨"))
(((command_name) @Conceal (#eq? @Conceal "\\implies")) (#set! conceal "⇒"))
(((command_name) @Conceal (#eq? @Conceal "\\impliedby")) (#set! conceal "⟸"))
(((command_name) @Conceal (#eq? @Conceal "\\iff")) (#set! conceal "⇔"))

(((command_name) @Conceal (#eq? @Conceal "\\equiv")) (#set! conceal "≡"))
(((command_name) @Conceal (#eq? @Conceal "\\ldotp")) (#set! conceal "."))

(((command_name) @Conceal (#eq? @Conceal "\\models")) (#set! conceal "⊨"))

; Sets
(((command_name) @Conceal (#eq? @Conceal "\\cap")) (#set! conceal "∩"))
(((command_name) @Conceal (#eq? @Conceal "\\cup")) (#set! conceal "∪"))
(((command_name) @Conceal (#eq? @Conceal "\\bigcap")) (#set! conceal "⋂"))
(((command_name) @Conceal (#eq? @Conceal "\\bigcup")) (#set! conceal "⋃"))

(((command_name) @Conceal (#eq? @Conceal "\\empty")) (#set! conceal "Ø"))
(((command_name) @Conceal (#eq? @Conceal "\\emptyset")) (#set! conceal "Ø"))
(((command_name) @Conceal (#eq? @Conceal "\\subseteq")) (#set! conceal "⊆"))
(((command_name) @Conceal (#eq? @Conceal "\\supseteq")) (#set! conceal "⊇"))
(((command_name) @Conceal (#eq? @Conceal "\\subset")) (#set! conceal "⊂"))
(((command_name) @Conceal (#eq? @Conceal "\\supset")) (#set! conceal "⊃"))

(((command_name) @Conceal (#eq? @Conceal "\\in")) (#set! conceal "∈"))
(((command_name) @Conceal (#eq? @Conceal "\\notin")) (#set! conceal "∉"))
(((command_name) @Conceal (#eq? @Conceal "\\ni")) (#set! conceal "∋"))
; notni has no unicode symbol
(((command_name) @Conceal (#eq? @Conceal "\\setminus")) (#set! conceal "⧵"))

(((command_name) @Conceal (#eq? @Conceal "\\biguplus")) (#set! conceal "⨄"))

; Arithmetic Big Operators
(((command_name) @Conceal (#eq? @Conceal "\\sum")) (#set! conceal "∑"))
(((command_name) @Conceal (#eq? @Conceal "\\prod")) (#set! conceal "∏"))
(((command_name) @Conceal (#eq? @Conceal "\\int")) (#set! conceal "∫"))
(((command_name) @Conceal (#eq? @Conceal "\\coprod")) (#set! conceal "∐"))

(((command_name) @Conceal (#eq? @Conceal "\\oint")) (#set! conceal "∮"))
(((command_name) @Conceal (#eq? @Conceal "\\iint")) (#set! conceal "∬"))
(((command_name) @Conceal (#eq? @Conceal "\\iiint")) (#set! conceal "∭"))
(((command_name) @Conceal (#eq? @Conceal "\\intop")) (#set! conceal "∫"))
(((command_name) @Conceal (#eq? @Conceal "\\smallint")) (#set! conceal "∫"))

(((command_name) @Conceal (#eq? @Conceal "\\bigotimes")) (#set! conceal "⨂"))
(((command_name) @Conceal (#eq? @Conceal "\\bigoplus")) (#set! conceal "⨁"))
(((command_name) @Conceal (#eq? @Conceal "\\bigodot")) (#set! conceal "⨀"))

; Relations
(((command_name) @Conceal (#eq? @Conceal "\\ne")) (#set! conceal "≠"))
(((command_name) @Conceal (#eq? @Conceal "\\neq")) (#set! conceal "≠"))
(((command_name) @Conceal (#eq? @Conceal "\\noteq")) (#set! conceal "≠"))
(((command_name) @Conceal (#eq? @Conceal "\\le")) (#set! conceal "≤"))
(((command_name) @Conceal (#eq? @Conceal "\\leq")) (#set! conceal "≤"))
(((command_name) @Conceal (#eq? @Conceal "\\let")) (#set! conceal "<"))
(((command_name) @Conceal (#eq? @Conceal "\\ge")) (#set! conceal "≥"))
(((command_name) @Conceal (#eq? @Conceal "\\geq")) (#set! conceal "≥"))
(((command_name) @Conceal (#eq? @Conceal "\\gt")) (#set! conceal ">"))

; Lattices
(((command_name) @Conceal (#eq? @Conceal "\\top")) (#set! conceal "⊤"))
(((command_name) @Conceal (#eq? @Conceal "\\bot")) (#set! conceal "⊥"))

(((command_name) @Conceal (#eq? @Conceal "\\sqsubseteq")) (#set! conceal "⊑"))
(((command_name) @Conceal (#eq? @Conceal "\\sqsupseteq")) (#set! conceal "⊒"))
(((command_name) @Conceal (#eq? @Conceal "\\sqsubset")) (#set! conceal "⊏"))
(((command_name) @Conceal (#eq? @Conceal "\\sqsupset")) (#set! conceal "⊐"))
(((command_name) @Conceal (#eq? @Conceal "\\sqcap")) (#set! conceal "⊓"))
(((command_name) @Conceal (#eq? @Conceal "\\sqcup")) (#set! conceal "⊔"))
(((command_name) @Conceal (#eq? @Conceal "\\Sqcap")) (#set! conceal "⩎"))
(((command_name) @Conceal (#eq? @Conceal "\\Sqcup")) (#set! conceal "⩏"))
(((command_name) @Conceal (#eq? @Conceal "\\bigsqcap")) (#set! conceal "⨅"))
(((command_name) @Conceal (#eq? @Conceal "\\bigsqcup")) (#set! conceal "⨆"))

; Arrows
(((command_name) @Conceal (#eq? @Conceal "\\to")) (#set! conceal "→"))
(((command_name) @Conceal (#eq? @Conceal "\\gets")) (#set! conceal "←"))
(((command_name) @Conceal (#eq? @Conceal "\\mapsto")) (#set! conceal "↦"))
(((command_name) @Conceal (#eq? @Conceal "\\leftrightarrow")) (#set! conceal "↔"))

; Brackets
(((command_name) @Conceal (#eq? @Conceal "\\llbracket")) (#set! conceal "⟦"))
(((command_name) @Conceal (#eq? @Conceal "\\rrbracket")) (#set! conceal "⟧"))

(((command_name) @Conceal (#eq? @Conceal "\\langle")) (#set! conceal "⟨"))
(((command_name) @Conceal (#eq? @Conceal "\\rangle")) (#set! conceal "⟩"))

; Fractions
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{4}")) (#set! conceal "¼"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{2}")) (#set! conceal "½"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{3}{4}")) (#set! conceal "¾"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{7}")) (#set! conceal "⅐"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{9}")) (#set! conceal "⅑"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{10}")) (#set! conceal "⅒"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{3}")) (#set! conceal "⅓"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{2}{3}")) (#set! conceal "⅔"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{5}")) (#set! conceal "⅕"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{2}{5}")) (#set! conceal "⅖"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{3}{5}")) (#set! conceal "⅗"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{4}{5}")) (#set! conceal "⅘"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{6}")) (#set! conceal "⅙"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{5}{6}")) (#set! conceal "⅚"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{1}{8}")) (#set! conceal "⅛"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{3}{8}")) (#set! conceal "⅜"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{5}{8}")) (#set! conceal "⅝"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{7}{8}")) (#set! conceal "⅞"))
(((generic_command) @Conceal (#eq? @Conceal "\\frac{0}{3}")) (#set! conceal "↉"))

; Other
(((command_name) @Conceal (#eq? @Conceal "\\flat")) (#set! conceal "♭"))
(((command_name) @Conceal (#eq? @Conceal "\\natural")) (#set! conceal "♮"))
(((command_name) @Conceal (#eq? @Conceal "\\sharp")) (#set! conceal "♯"))

(((command_name) @Conceal (#eq? @Conceal "\\square")) (#set! conceal "□"))
(((command_name) @Conceal (#eq? @Conceal "\\blacksquare")) (#set! conceal "■"))
(((command_name) @Conceal (#eq? @Conceal "\\Box")) (#set! conceal "□"))

(((command_name) @Conceal (#eq? @Conceal "\\mid")) (#set! conceal "∣"))
(((command_name) @Conceal (#eq? @Conceal "\\dots")) (#set! conceal "…"))
(((command_name) @Conceal (#eq? @Conceal "\\cdots")) (#set! conceal "⋯"))
(((command_name) @Conceal (#eq? @Conceal "\\vdots")) (#set! conceal "⋮"))

(((command_name) @Conceal (#eq? @Conceal "\\coloneqq")) (#set! conceal "≔"))
(((command_name) @Conceal (#eq? @Conceal "\\circ")) (#set! conceal "∘"))
(((command_name) @Conceal (#eq? @Conceal "\\oplus")) (#set! conceal "⊕"))
(((command_name) @Conceal (#eq? @Conceal "\\infty")) (#set! conceal "∞"))
(((command_name) @Conceal (#eq? @Conceal "\\nabla")) (#set! conceal "∇"))

; Escaped Characters
(((command_name) @Conceal (#eq? @Conceal "\\_")) (#set! conceal "_"))
(((command_name) @Conceal (#eq? @Conceal "\\{")) (#set! conceal "{"))
(((command_name) @Conceal (#eq? @Conceal "\\}")) (#set! conceal "}"))
(((command_name) @Conceal (#eq? @Conceal "\\%")) (#set! conceal "%"))
(((command_name) @Conceal (#eq? @Conceal "\\#")) (#set! conceal "#"))
(((command_name) @Conceal (#eq? @Conceal "\\&")) (#set! conceal "&"))
(((command_name) @Conceal (#eq? @Conceal "\\$")) (#set! conceal "$"))

; Greek Letters
(((command_name) @Conceal (#eq? @Conceal "\\Alpha")) (#set! conceal "Α"))
(((command_name) @Conceal (#eq? @Conceal "\\Beta")) (#set! conceal "Β"))
(((command_name) @Conceal (#eq? @Conceal "\\Gamma")) (#set! conceal "Γ"))
(((command_name) @Conceal (#eq? @Conceal "\\Delta")) (#set! conceal "Δ"))
(((command_name) @Conceal (#eq? @Conceal "\\Epsilon")) (#set! conceal "Ε"))
(((command_name) @Conceal (#eq? @Conceal "\\Zeta")) (#set! conceal "Ζ"))
(((command_name) @Conceal (#eq? @Conceal "\\Eta")) (#set! conceal "Η"))
(((command_name) @Conceal (#eq? @Conceal "\\Theta")) (#set! conceal "Θ"))
(((command_name) @Conceal (#eq? @Conceal "\\Iota")) (#set! conceal "Ι"))
(((command_name) @Conceal (#eq? @Conceal "\\Kappa")) (#set! conceal "Κ"))
(((command_name) @Conceal (#eq? @Conceal "\\Lambda")) (#set! conceal "Λ"))
(((command_name) @Conceal (#eq? @Conceal "\\Mu")) (#set! conceal "Μ"))
(((command_name) @Conceal (#eq? @Conceal "\\Nu")) (#set! conceal "Ν"))
(((command_name) @Conceal (#eq? @Conceal "\\Xi")) (#set! conceal "Ξ"))
(((command_name) @Conceal (#eq? @Conceal "\\Omicron")) (#set! conceal "Ο"))
(((command_name) @Conceal (#eq? @Conceal "\\Pi")) (#set! conceal "Π"))
(((command_name) @Conceal (#eq? @Conceal "\\Rho")) (#set! conceal "Ρ"))
(((command_name) @Conceal (#eq? @Conceal "\\Sigma")) (#set! conceal "Σ"))
(((command_name) @Conceal (#eq? @Conceal "\\Tau")) (#set! conceal "Τ"))
(((command_name) @Conceal (#eq? @Conceal "\\Upsilon")) (#set! conceal "Υ"))
(((command_name) @Conceal (#eq? @Conceal "\\Phi")) (#set! conceal "Φ"))
(((command_name) @Conceal (#eq? @Conceal "\\Chi")) (#set! conceal "Χ"))
(((command_name) @Conceal (#eq? @Conceal "\\Psi")) (#set! conceal "Ε"))
(((command_name) @Conceal (#eq? @Conceal "\\Omega")) (#set! conceal "Ω"))

(((command_name) @Conceal (#eq? @Conceal "\\alpha")) (#set! conceal "α"))
(((command_name) @Conceal (#eq? @Conceal "\\beta")) (#set! conceal "β"))
(((command_name) @Conceal (#eq? @Conceal "\\gamma")) (#set! conceal "γ"))
(((command_name) @Conceal (#eq? @Conceal "\\delta")) (#set! conceal "δ"))
(((command_name) @Conceal (#eq? @Conceal "\\epsilon")) (#set! conceal "ε"))
(((command_name) @Conceal (#eq? @Conceal "\\zeta")) (#set! conceal "ζ"))
(((command_name) @Conceal (#eq? @Conceal "\\eta")) (#set! conceal "η"))
(((command_name) @Conceal (#eq? @Conceal "\\theta")) (#set! conceal "θ"))
(((command_name) @Conceal (#eq? @Conceal "\\iota")) (#set! conceal "ι"))
(((command_name) @Conceal (#eq? @Conceal "\\kappa")) (#set! conceal "κ"))
(((command_name) @Conceal (#eq? @Conceal "\\lambda")) (#set! conceal "λ"))
(((command_name) @Conceal (#eq? @Conceal "\\mu")) (#set! conceal "μ"))
(((command_name) @Conceal (#eq? @Conceal "\\nu")) (#set! conceal "ν"))
(((command_name) @Conceal (#eq? @Conceal "\\xi")) (#set! conceal "ξ"))
(((command_name) @Conceal (#eq? @Conceal "\\omicron")) (#set! conceal "ο"))
(((command_name) @Conceal (#eq? @Conceal "\\pi")) (#set! conceal "π"))
(((command_name) @Conceal (#eq? @Conceal "\\rho")) (#set! conceal "ρ"))
(((command_name) @Conceal (#eq? @Conceal "\\sigma")) (#set! conceal "σ"))
(((command_name) @Conceal (#eq? @Conceal "\\tau")) (#set! conceal "τ"))
(((command_name) @Conceal (#eq? @Conceal "\\upsilon")) (#set! conceal "υ"))
(((command_name) @Conceal (#eq? @Conceal "\\phi")) (#set! conceal "φ"))
(((command_name) @Conceal (#eq? @Conceal "\\chi")) (#set! conceal "χ"))
(((command_name) @Conceal (#eq? @Conceal "\\psi")) (#set! conceal "ψ"))
(((command_name) @Conceal (#eq? @Conceal "\\omega")) (#set! conceal "ω"))

(((command_name) @Conceal (#eq? @Conceal "\\varsigma")) (#set! conceal "ς"))

; mathbb letters
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{0}")) (#set! conceal "𝟘"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{1}")) (#set! conceal "𝟙"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{2}")) (#set! conceal "𝟚"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{3}")) (#set! conceal "𝟛"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{4}")) (#set! conceal "𝟜"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{5}")) (#set! conceal "𝟝"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{6}")) (#set! conceal "𝟞"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{7}")) (#set! conceal "𝟟"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{8}")) (#set! conceal "𝟠"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{9}")) (#set! conceal "𝟡"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{A}")) (#set! conceal "𝔸"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{B}")) (#set! conceal "𝔹"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{C}")) (#set! conceal "ℂ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{D}")) (#set! conceal "𝔻"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{E}")) (#set! conceal "𝔼"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{F}")) (#set! conceal "𝔽"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{G}")) (#set! conceal "𝔾"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{H}")) (#set! conceal "ℍ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{I}")) (#set! conceal "𝕀"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{J}")) (#set! conceal "𝕁"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{K}")) (#set! conceal "𝕂"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{L}")) (#set! conceal "𝕃"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{M}")) (#set! conceal "𝕄"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{N}")) (#set! conceal "ℕ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{O}")) (#set! conceal "𝕆"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{P}")) (#set! conceal "ℙ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{Q}")) (#set! conceal "ℚ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{R}")) (#set! conceal "ℝ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{S}")) (#set! conceal "𝕊"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{T}")) (#set! conceal "𝕋"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{U}")) (#set! conceal "𝕌"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{V}")) (#set! conceal "𝕍"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{W}")) (#set! conceal "𝕎"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{X}")) (#set! conceal "𝕏"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{Y}")) (#set! conceal "𝕐"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{Z}")) (#set! conceal "ℤ"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{a}")) (#set! conceal "𝕒"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{b}")) (#set! conceal "𝕓"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{c}")) (#set! conceal "𝕔"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{d}")) (#set! conceal "𝕕"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{e}")) (#set! conceal "𝕖"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{f}")) (#set! conceal "𝕗"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{g}")) (#set! conceal "𝕘"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{h}")) (#set! conceal "𝕙"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{i}")) (#set! conceal "𝕚"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{j}")) (#set! conceal "𝕛"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{k}")) (#set! conceal "𝕜"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{l}")) (#set! conceal "𝕝"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{m}")) (#set! conceal "𝕞"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{n}")) (#set! conceal "𝕟"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{o}")) (#set! conceal "𝕠"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{p}")) (#set! conceal "𝕡"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{q}")) (#set! conceal "𝕢"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{r}")) (#set! conceal "𝕣"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{s}")) (#set! conceal "𝕤"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{t}")) (#set! conceal "𝕥"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{u}")) (#set! conceal "𝕦"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{v}")) (#set! conceal "𝕧"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{w}")) (#set! conceal "𝕨"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{x}")) (#set! conceal "𝕩"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{y}")) (#set! conceal "𝕪"))
(((generic_command) @Conceal (#eq? @Conceal "\\mathbb{z}")) (#set! conceal "𝕫"))

; Subscripts
(((subscript) @Conceal (#eq? @Conceal "_\\beta")) (#set! conceal "ᵦ"))
(((subscript) @Conceal (#eq? @Conceal "_\\rho")) (#set! conceal "ᵨ"))
(((subscript) @Conceal (#eq? @Conceal "_\\phi")) (#set! conceal "ᵩ"))
(((subscript) @Conceal (#eq? @Conceal "_\\gamma")) (#set! conceal "ᵧ"))
(((subscript) @Conceal (#eq? @Conceal "_\\chi")) (#set! conceal "ᵪ"))

(((subscript) @Conceal (#eq? @Conceal "_0")) (#set! conceal "₀"))
(((subscript) @Conceal (#eq? @Conceal "_1")) (#set! conceal "₁"))
(((subscript) @Conceal (#eq? @Conceal "_2")) (#set! conceal "₂"))
(((subscript) @Conceal (#eq? @Conceal "_3")) (#set! conceal "₃"))
(((subscript) @Conceal (#eq? @Conceal "_4")) (#set! conceal "₄"))
(((subscript) @Conceal (#eq? @Conceal "_5")) (#set! conceal "₅"))
(((subscript) @Conceal (#eq? @Conceal "_6")) (#set! conceal "₆"))
(((subscript) @Conceal (#eq? @Conceal "_7")) (#set! conceal "₇"))
(((subscript) @Conceal (#eq? @Conceal "_8")) (#set! conceal "₈"))
(((subscript) @Conceal (#eq? @Conceal "_9")) (#set! conceal "₉"))

(((subscript) @Conceal (#eq? @Conceal "_a")) (#set! conceal "ₐ"))
(((subscript) @Conceal (#eq? @Conceal "_e")) (#set! conceal "ₑ"))
(((subscript) @Conceal (#eq? @Conceal "_h")) (#set! conceal "ₕ"))
(((subscript) @Conceal (#eq? @Conceal "_i")) (#set! conceal "ᵢ"))
(((subscript) @Conceal (#eq? @Conceal "_j")) (#set! conceal "ⱼ"))
(((subscript) @Conceal (#eq? @Conceal "_k")) (#set! conceal "ₖ"))
(((subscript) @Conceal (#eq? @Conceal "_l")) (#set! conceal "ₗ"))
(((subscript) @Conceal (#eq? @Conceal "_m")) (#set! conceal "ₘ"))
(((subscript) @Conceal (#eq? @Conceal "_n")) (#set! conceal "ₙ"))
(((subscript) @Conceal (#eq? @Conceal "_o")) (#set! conceal "ₒ"))
(((subscript) @Conceal (#eq? @Conceal "_p")) (#set! conceal "ₚ"))
(((subscript) @Conceal (#eq? @Conceal "_r")) (#set! conceal "ᵣ"))
(((subscript) @Conceal (#eq? @Conceal "_s")) (#set! conceal "ₛ"))
(((subscript) @Conceal (#eq? @Conceal "_t")) (#set! conceal "ₜ"))
(((subscript) @Conceal (#eq? @Conceal "_u")) (#set! conceal "ᵤ"))
(((subscript) @Conceal (#eq? @Conceal "_v")) (#set! conceal "ᵥ"))
(((subscript) @Conceal (#eq? @Conceal "_x")) (#set! conceal "ₓ"))

(((subscript) @Conceal (#eq? @Conceal "_+")) (#set! conceal "₊"))
(((subscript) @Conceal (#eq? @Conceal "_-")) (#set! conceal "₋"))
(((subscript) @Conceal (#eq? @Conceal "_=")) (#set! conceal "₌"))
(((subscript) @Conceal (#eq? @Conceal "_(")) (#set! conceal "₍"))
(((subscript) @Conceal (#eq? @Conceal "_)")) (#set! conceal "₎"))

; Superscripts
(((subscript) @Conceal (#eq? @Conceal "^0")) (#set! conceal "⁰"))
(((subscript) @Conceal (#eq? @Conceal "^1")) (#set! conceal "¹"))
(((subscript) @Conceal (#eq? @Conceal "^2")) (#set! conceal "²"))
(((subscript) @Conceal (#eq? @Conceal "^3")) (#set! conceal "³"))
(((subscript) @Conceal (#eq? @Conceal "^4")) (#set! conceal "⁴"))
(((subscript) @Conceal (#eq? @Conceal "^5")) (#set! conceal "⁵"))
(((subscript) @Conceal (#eq? @Conceal "^6")) (#set! conceal "⁶"))
(((subscript) @Conceal (#eq? @Conceal "^7")) (#set! conceal "⁷"))
(((subscript) @Conceal (#eq? @Conceal "^8")) (#set! conceal "⁸"))
(((subscript) @Conceal (#eq? @Conceal "^9")) (#set! conceal "⁹"))

(((subscript) @Conceal (#eq? @Conceal "^+")) (#set! conceal "⁺"))
(((subscript) @Conceal (#eq? @Conceal "^-")) (#set! conceal "⁻"))
(((subscript) @Conceal (#eq? @Conceal "^=")) (#set! conceal "⁼"))
(((subscript) @Conceal (#eq? @Conceal "^(")) (#set! conceal "⁽"))
(((subscript) @Conceal (#eq? @Conceal "^)")) (#set! conceal "⁾"))

(((subscript) @Conceal (#eq? @Conceal "^a")) (#set! conceal "ᵃ"))
(((subscript) @Conceal (#eq? @Conceal "^b")) (#set! conceal "ᵇ"))
(((subscript) @Conceal (#eq? @Conceal "^c")) (#set! conceal "ᶜ"))
(((subscript) @Conceal (#eq? @Conceal "^d")) (#set! conceal "ᵈ"))
(((subscript) @Conceal (#eq? @Conceal "^e")) (#set! conceal "ᵉ"))
(((subscript) @Conceal (#eq? @Conceal "^f")) (#set! conceal "ᶠ"))
(((subscript) @Conceal (#eq? @Conceal "^g")) (#set! conceal "ᵍ"))
(((subscript) @Conceal (#eq? @Conceal "^h")) (#set! conceal "ʰ"))
(((subscript) @Conceal (#eq? @Conceal "^i")) (#set! conceal "ⁱ"))
(((subscript) @Conceal (#eq? @Conceal "^j")) (#set! conceal "ʲ"))
(((subscript) @Conceal (#eq? @Conceal "^k")) (#set! conceal "ᵏ"))
(((subscript) @Conceal (#eq? @Conceal "^l")) (#set! conceal "ˡ"))
(((subscript) @Conceal (#eq? @Conceal "^m")) (#set! conceal "ᵐ"))
(((subscript) @Conceal (#eq? @Conceal "^n")) (#set! conceal "ⁿ"))
(((subscript) @Conceal (#eq? @Conceal "^o")) (#set! conceal "ᵒ"))
(((subscript) @Conceal (#eq? @Conceal "^p")) (#set! conceal "ᵖ"))
(((subscript) @Conceal (#eq? @Conceal "^q")) (#set! conceal "𐞥"))
(((subscript) @Conceal (#eq? @Conceal "^r")) (#set! conceal "ʳ"))
(((subscript) @Conceal (#eq? @Conceal "^s")) (#set! conceal "ˢ"))
(((subscript) @Conceal (#eq? @Conceal "^t")) (#set! conceal "ᵗ"))
(((subscript) @Conceal (#eq? @Conceal "^u")) (#set! conceal "ᵘ"))
(((subscript) @Conceal (#eq? @Conceal "^v")) (#set! conceal "ᵛ"))
(((subscript) @Conceal (#eq? @Conceal "^w")) (#set! conceal "ʷ"))
(((subscript) @Conceal (#eq? @Conceal "^x")) (#set! conceal "ˣ"))
(((subscript) @Conceal (#eq? @Conceal "^y")) (#set! conceal "ʸ"))
(((subscript) @Conceal (#eq? @Conceal "^z")) (#set! conceal "ᶻ"))

(((subscript) @Conceal (#eq? @Conceal "^A")) (#set! conceal "ᴬ"))
(((subscript) @Conceal (#eq? @Conceal "^B")) (#set! conceal "ᴮ"))
(((subscript) @Conceal (#eq? @Conceal "^C")) (#set! conceal "ꟲ"))
(((subscript) @Conceal (#eq? @Conceal "^D")) (#set! conceal "ᴰ"))
(((subscript) @Conceal (#eq? @Conceal "^E")) (#set! conceal "ᴱ"))
(((subscript) @Conceal (#eq? @Conceal "^F")) (#set! conceal "ꟳ"))
(((subscript) @Conceal (#eq? @Conceal "^G")) (#set! conceal "ᴳ"))
(((subscript) @Conceal (#eq? @Conceal "^H")) (#set! conceal "ᴴ"))
(((subscript) @Conceal (#eq? @Conceal "^I")) (#set! conceal "ᴵ"))
(((subscript) @Conceal (#eq? @Conceal "^J")) (#set! conceal "ᴶ"))
(((subscript) @Conceal (#eq? @Conceal "^K")) (#set! conceal "ᴷ"))
(((subscript) @Conceal (#eq? @Conceal "^L")) (#set! conceal "ᴸ"))
(((subscript) @Conceal (#eq? @Conceal "^M")) (#set! conceal "ᴹ"))
(((subscript) @Conceal (#eq? @Conceal "^N")) (#set! conceal "ᴺ"))
(((subscript) @Conceal (#eq? @Conceal "^O")) (#set! conceal "ᴼ"))
(((subscript) @Conceal (#eq? @Conceal "^P")) (#set! conceal "ᴾ"))
(((subscript) @Conceal (#eq? @Conceal "^Q")) (#set! conceal "ꟴ"))
(((subscript) @Conceal (#eq? @Conceal "^R")) (#set! conceal "ᴿ"))
(((subscript) @Conceal (#eq? @Conceal "^T")) (#set! conceal "ᵀ"))
(((subscript) @Conceal (#eq? @Conceal "^U")) (#set! conceal "ᵁ"))
(((subscript) @Conceal (#eq? @Conceal "^V")) (#set! conceal "ⱽ"))
(((subscript) @Conceal (#eq? @Conceal "^W")) (#set! conceal "ᵂ"))


; ===== Custom =====

(((command_name) @Conceal (#eq? @Conceal "\\A")) (#set! conceal "𝔸"))
(((command_name) @Conceal (#eq? @Conceal "\\B")) (#set! conceal "𝔹"))
(((command_name) @Conceal (#eq? @Conceal "\\C")) (#set! conceal "ℂ"))
(((command_name) @Conceal (#eq? @Conceal "\\D")) (#set! conceal "𝔻"))
(((command_name) @Conceal (#eq? @Conceal "\\E")) (#set! conceal "𝔼"))
(((command_name) @Conceal (#eq? @Conceal "\\F")) (#set! conceal "𝔽"))
(((command_name) @Conceal (#eq? @Conceal "\\G")) (#set! conceal "𝔾"))
(((command_name) @Conceal (#eq? @Conceal "\\H")) (#set! conceal "ℍ"))
(((command_name) @Conceal (#eq? @Conceal "\\I")) (#set! conceal "𝕀"))
(((command_name) @Conceal (#eq? @Conceal "\\J")) (#set! conceal "𝕁"))
(((command_name) @Conceal (#eq? @Conceal "\\K")) (#set! conceal "𝕂"))
(((command_name) @Conceal (#eq? @Conceal "\\L")) (#set! conceal "𝕃"))
(((command_name) @Conceal (#eq? @Conceal "\\M")) (#set! conceal "𝕄"))
(((command_name) @Conceal (#eq? @Conceal "\\N")) (#set! conceal "ℕ"))
(((command_name) @Conceal (#eq? @Conceal "\\O")) (#set! conceal "𝕆"))
(((command_name) @Conceal (#eq? @Conceal "\\P")) (#set! conceal "ℙ"))
(((command_name) @Conceal (#eq? @Conceal "\\Q")) (#set! conceal "ℚ"))
(((command_name) @Conceal (#eq? @Conceal "\\R")) (#set! conceal "ℝ"))
(((command_name) @Conceal (#eq? @Conceal "\\S")) (#set! conceal "𝕊"))
(((command_name) @Conceal (#eq? @Conceal "\\T")) (#set! conceal "𝕋"))
(((command_name) @Conceal (#eq? @Conceal "\\U")) (#set! conceal "𝕌"))
(((command_name) @Conceal (#eq? @Conceal "\\V")) (#set! conceal "𝕍"))
(((command_name) @Conceal (#eq? @Conceal "\\W")) (#set! conceal "𝕎"))
(((command_name) @Conceal (#eq? @Conceal "\\X")) (#set! conceal "𝕏"))
(((command_name) @Conceal (#eq? @Conceal "\\Y")) (#set! conceal "𝕐"))
(((command_name) @Conceal (#eq? @Conceal "\\Z")) (#set! conceal "ℤ"))

(((command_name) @Conceal (#eq? @Conceal "\\binDelta")) (#set! conceal "Δ"))
(((command_name) @Conceal (#eq? @Conceal "\\binsquare")) (#set! conceal "□"))
