#!/bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
    mouse_follows_focus on \
    focus_follows_mouse autoraise \
\
    window_origin_display cursor \
    window_placement second_child \
    window_zoom_persist on \
    window_shadow on \
    window_opacity on \
    window_opacity_duration 0.5 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.9 \
    window_animation_duration 0.0 \
    window_animation_frame_rate 120 \
\
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.5 \
    split_type auto \
    auto_balance off \
\
    mouse_modifier alt \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
\
    layout bsp \
    top_padding 12 \
    bottom_padding 12 \
    left_padding 12 \
    right_padding 12 \
    window_gap 6

# yabai -m rule --add label=finder app=Finder manage=off

echo "yabai configuration loaded"
echo "starting sketchybar"
sketchybar &

